# Configures global blog settings. Values from this file may be accessed
# elsewhere using {{ site.title }}, {{ site.email }}, and so on.

title: blog.blanke.dev
email: andre@blanke.dev
url: "https://blog.blanke.dev"
github_username: andreblanke

# Build settings
theme: minima
plugins:
  - jekyll-feed
